### ISSUE TITLE
add source to git

### ISSUE THREAD

**Issue by joachimmetz** [libyal/libtableau#1]
* [x] rename AMOUNT to NUMBER
* [x] migrate allocate to initialize
* [x] migrate old code to use libcerror
  * migrate use of notify to libcerror
* [x] migrate old code to use libcnotify

**Comment by jimuk** [comment]
This repo is empty. It would be great to see some code here for working with Tableau forensic bridges.

**Comment by joachimmetz** [comment]
@jimuk the source will be added when time permits.

**Comment by joachimmetz** [comment]
@jimuk an updated version of the original source has been added to the repo
